alivx/CIS-Ubuntu-20.04-Ansible

- defaults/main.yml
- tasks/section_1_Initial_Setup.yaml
- tasks/section_5_Access_Authentication_and_Authorization.yaml
- Instead of hardcoding the value in the playbook file (tests 5.2.21 and 5.2.22), it'd be better to allow the value to be configured in the main.yml file, fore easy customisation.
- Also resolves a warning in tasks/section_1_Initial_Setup.yaml 
Issue: alivx/CIS-Ubuntu-20.04-Ansible#6
> (feature) Allow for customisation of SSH MaxStartups and MaxSessions

- defaults/main.yml
- tasks/section_5_Access_Authentication_and_Authorization.yaml
In some cases, hardening of ssh/scp should allow the explicit use of weaker protocols, for instance when other servers that connect to the hardened server don't possess certain strong protocols and as a consequence, can't connect amymore.
This can be implemented by allowing the MAC and KexAlgorithms to be defined/overwritten from the configuration.
For instance:
In `main.yml`:
```
ssh_MACs: "hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,_hmac-sha1-96_"
ssh_key_algorithms: "curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256,_diffie-hellman-group14-sha1_"
```
```
- name: …
```
> (feature) Allows configuration of SSH MACs and KexAlgorithms.

- tasks/section_5_Access_Authentication_and_Authorization.yaml
Test 5.4.5: As seen in other hardenings, the TMOUT can be set readonly before exporting.
> (feature) Set TMOUT variables as readonly in test 5.4.5

- tasks/section_1_Initial_Setup.yaml
A few recommended settings in `/etc/coredump.conf` were omitted. This PR adds them, as per the recommendations:
```
Solution: Add the following line to /etc/security/limits.conf or a /etc/security/limits.d/* file:
* hard core 0
Set the following parameter in /etc/sysctl.conf or a /etc/sysctl.d/* file:
fs.suid_dumpable = 0
Run the following command to set the active kernel parameter:
If systemd-coredump is installed:         
edit /etc/systemd/coredump.conf and add/modify the following lines:   <-----------
Storage=none
ProcessSizeMax=0
Run the command:
systemctl daemon-reload
```
> (feature) [COTEF1901-104] Improved test 1.6.4 (coredump.conf)

- .travis.yml
Addresses deprecation warning in Travis Build
```
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
```
#25
> Update Travs CI build

- defaults/main.yml
- tasks/section_1_Initial_Setup.yaml
Sometimes it's needed to have different templates for different customers. This feature allows for overwriting the default template (in `files/templates/motd.j2`) with an external file, by setting a variable pointing to that file. 
If the file doesn't exist, the default template will be used.
> (feature) Improve motd message by allowing the use of an external template

- tasks/section_3_Network_Configuration.yaml
`enable_firewall` should apply to all ufw rules in task 3.5.1.7
The following task didn't have the "when: enable_firewall" condition set.
```
- name: Enable UFW
ufw:
state: enabled
policy: allow
```
> (bugfix) [3.5.1.7] 'enable_firewall' flag applied to all 'ufw' tasks

- tasks/section_3_Network_Configuration.yaml
The following task might fail if no ipv6 is provided, so only execute it when `IPv6_is_enabled` flag is set.
```
- name: 3.3.9 Ensure IPv6 router advertisements are not accepted | load	    - name: 3.3.9 Ensure IPv6 router advertisements are not accepted | load
shell: |	      shell: |
sysctl -w net.ipv6.conf.all.accept_ra=0	        sysctl -w net.ipv6.conf.all.accept_ra=0
sysctl -w net.ipv6.conf.default.accept_ra=0	        sysctl -w net.ipv6.conf.default.accept_ra=0
sysctl -w net.ipv6.route.flush=1
```
> (bugfix) [3.3.9] Only execute ipv6 commands when 'IPv6_is_enabled' is set

- tasks/section_3_Network_Configuration.yaml
The following task might fail when ipv6 is not enabled (`IPv6_is_enabled`):
```
- name: 3.3.1 Ensure source routed packets are not accepted | ipv6 load"
shell: |
sysctl -w net.ipv6.conf.all.accept_source_route=0
sysctl -w net.ipv6.conf.default.accept_source_route=0
sysctl -w net.ipv6.route.flush=1
```
> (bugfix) [3.3.1] Only execute ipv6 commands when 'IPv6_is_enabled' is set

- tasks/section_5_Access_Authentication_and_Authorization.yaml
The following task should not fail if a user in the list `list_of_os_users` doesn't exist, instead it should continue with the next user in the list.
```
- name: 5.4.1.4 Ensure inactive password lock is 30 days or less
block:
- name: 5.4.1.4 Ensure inactive password lock is 30 days or less | useradd
command: "useradd -D -f {{ account_inactive }}"
- name: 5.4.1.4 Ensure inactive password lock is 30 days or less | useradd
command: "chage --inactive {{ account_inactive }} {{ item }}"
with_items: "{{ list_of_os_users }}"
```
> (bugfix) [5.4.1.4] Task shouldn't fail if user in list doesn't exist

- tasks/section_5_Access_Authentication_and_Authorization.yaml
If a user mentioned in the list `list_of_os_users` doesn't exist in the destination server for task 5.4.1.1, the task should not abort but simply continue with other users:
```
- name: 5.4.1.1 Ensure password expiration is 365 days or less\
5.4.1.2 Ensure minimum days between password changes is configured\n
5.4.1.3 Ensure password expiration warning days is 7 or more"
block:
- name: 5.4.1.1 Ensure password expiration is 365 days or less | PASS_MAX_DAYS
lineinfile:
state: present
dest: /etc/login.defs
regexp: "^PASS_MAX_DAYS"
line: "PASS_MAX_DAYS {{ pass_expire_in_days }}"
- name: 5.4.1.1 Ensure password expiration is 365 days or less | PASS_MIN_DAYS
lineinfile:
state: present
dest: /etc/login.defs
regexp: "^PASS_MIN_DAYS"
line: "PASS_MIN_DAYS {{ pass_min_days }}"
- name: 5.4.1.1 Ensure …
```
> (bugfix) [5.4.1.1] Task shouldn't fail if user in list doesn't exist

- tasks/section_5_Access_Authentication_and_Authorization.yaml
Setting the TMOUT variable READONLY throws errors when entering the shell, because once set _readonly_, it's consecutively modified from within the other scrips
```
-bash: TMOUT: readonly variable
```
> (bugfix) [5.5.4] Remove readonly flags, throwing errors in shell, on TMOUT variable

- files/1.4.1.txt
- tasks/section_1_Initial_Setup.yaml
- Added options so that the execution doesn't get stuck on questions:
```
Overwrite existing /var/lib/aide/aide.db.new [Yn]? Y
Overwrite /var/lib/aide/aide.db [yN]? y
```
- Also added exclusion of directory "/var/lib/lxcfs/cgroup/"; it throws a lot of errors during the checks, example:
```
do_md(): open() for /var/lib/lxcfs/cgroup/memory/system.slice/systemd-modules-load.service/memory.pressure_level failed: Permission denied
```
Finally, I am not sure why the following task is needed:
```
- name: Configure AIDE as appropriate for your environment | aideinit db
shell: |
mv /var/lib/aide/aide.db.new /var/lib/aide/aide.db
```
> (feature) Avoids AIDE installation waiting eternally for input

- tasks/section_1_Initial_Setup.yaml
The default AIDE checksums might be a bit of overkill. This feature allows you to set a variable 
```
aide_checksums: "sha512"
```
so that only this checksum is executed.
> (feature) Allows for simplifying AIDE checksums

- defaults/main.yml
- tasks/section_3_Network_Configuration.yaml
- (feature) Adds optional keep_alived firewall rules to task 3.5.1.6
- (chore) Changes some "false" to "no", for consistency reasons. Adds some comments. Changes variable name to use "firewall" and not "ufw".
> (feature) Adds optional keep_alived firewall rules to task 3.5.1.6

- tasks/section_1_Initial_Setup.yaml
- tasks/section_2_Services.yaml
- tasks/section_5_Access_Authentication_and_Authorization.yaml
- tasks/section_6_System_Maintenance.yaml
As mentioned in issue #51 this branch implements renaming the `diy` tag to `manual` and adds the missing manual tag to `1.2.1 Ensure package manager repositories are configured`.
> Rename diy tag to manual

- tasks/section_1_Initial_Setup.yaml
Some checking systems complain when the package isn't completely removed from the system, so I've added a purge.
```
cmd: /usr/bin/dpkg -s autofs 2>&1 expect: package 'autofs' is not installed system: Linux
```
Question: should we add this for all `state: absent` apt calls?
> feature: Purges autofs completely

- defaults/main.yml
- tasks/section_6_System_Maintenance.yaml
CIS states for test 6.1.6:
> Run one of the following commands to set ownership of /etc/shadow to root and group to either root or shadow.
We used to set the group permissions to "shadow" but for better compatbility we should set it to "root".
> chore: Set group of /etc/shadow to root, for better compatibility

- defaults/main.yml
- tasks/section_5_Access_Authentication_and_Authorization.yaml
Allow root login from a certain list of IPs, only if the variable `ssh_root_login_ips` is not `None`
Example:
`ssh_root_login_ips: "192.168.10.10,192.168.1.0/24"`
In this case the `/etc/ssh/sshd_config` will contain a section:
``` 
Match Address 192.168.10.10,192.168.1.0/24
PermitRootLogin yes
```
> feature: Allows SSH root login from a certain list of IPs

- defaults/main.yml
- files/6_2_7_include_folders.sh
- tasks/section_6_System_Maintenance.yaml
Task 6.2.7 only checks for hidden files in home directories, not folders. I'm unsure if this is the intended behavior but I added an option to use an alternate script that does check for folders as well.
Some vulnerability checking software such as Nessus checks if folders in home directory are not group or world writable with this expression:
`awk -F: '($1!~/(halt|sync|shutdown)/ && $7!~/^(/usr)?/sbin/nologin(/)?$/ && $7!~/(/usr)?/bin/false(/)?$/) { print $1 ' ' $6 }' | while read -r user dir; do if [ -d '$dir' ]; then for file in '$dir'/.*; do if [ ! -h '$file' ] && [ -f '$file' ]; then fileperm=$(stat -L -c '%A' '$file') if [ '$(echo '$fileperm' | cut -c6)' != '-' ] || [ '$(echo '$fileperm' | cut -c9)' != '-' ]; then chmod go-w '$file'
fi fi done fi done`
So maybe this should be the …
> 6.2.7 include folders in hidden dot files search

- defaults/main.yml
- tasks/section_6_System_Maintenance.yaml
In some cases, it is desirable to skip certain files in task 6.1.11, as they may need to not be modified for some programs to keep working. This pull request creates an option to add the path of these files as comma separated strings. When the value of the variable is None, the task runs as normal.
> Adds the option to skip certain files in 6.1.11

- files/6_2_5.sh
- files/6_2_6.sh
- tasks/section_6_System_Maintenance.yaml
Commit [ea482867a8cff49db137fd20f69a2a1ac5779446](https://github.com/alivx/CIS-Ubuntu-20.04-Ansible/commit/ea482867a8cff49db137fd20f69a2a1ac5779446) brakes 6.2.5 and 6.2.6.
This PR switches the content of those scripts and fixes the variable names in those tasks.
> Fixes 6.2.5 & 6.2.6 script and tasks naming mix-up

- files/6_2_8.sh
- files/6_2_9.sh
- tasks/section_6_System_Maintenance.yaml
Task `6.2.8` was calling a script called `6.2.9.sh` which implemented the
requirements for task `6.2.8`. `6.2.9` was similarly calling script
`6.2.8.sh`. These tasks called the right script, but were called the
wrong thing. This pull request these typos.
I didn't see a place to update any version numbers in the README as described in the contributing guidelines, but let me know if there is a place I should do that.
> Fix task 6.2.8 running script 6.2.9 and vice versa

- defaults/main.yml
- tasks/section_6_System_Maintenance.yaml
Some scanning tools check to see if `/etc/shadow` has mode 0640 instead of 0600. Guidelines indicate the following:
"Access permission is 640 or more restrictive."
So 0640 should be an option as well.
> Adds a parameter to set the mode of /etc/shadow

- defaults/main.yml
- tasks/section_1_Initial_Setup.yaml
This PR adds task 1.4.1 in accordance to the CIS Ubuntu Linux 20.04 LTS Benchmark.
> Adds task 1.4.1 Ensure permissions on bootloader config are not overridden

- files/6_2_6.sh
- tasks/section_5_Access_Authentication_and_Authorization.yaml
Currently task 6.2.6 filters users with 
`$7 != "'"$(which nologin)"'" && $7 != "/bin/false"`
where $7 is usually one of these values
`/usr/sbin/nologin
/bin/false
/bin/bash`
This check fails if $7 takes the following value (for example)
`/sbin/nologin`
if `which nologin` cannot find this path, this user does not get filtered and causes errors in the script.
I've added an additional check for `"/nologin"` so that all users are correctly filtered.
> 6.2.6 Adds an extra filter in case of using a different nologin

- files/6_2_6.sh
- tasks/section_5_Access_Authentication_and_Authorization.yaml
Some automated vulnerability scanners such as Nessus match the `Match address` line with a lowercase 'a'. I've implemented a change to reflect this. I've also added matching with lower case 'a' and 'm' in the regex used.
> Adds better regex matching for task 5.3.10 and changes line for better compatibility with vulnerability scanners

- tasks/section_1_Initial_Setup.yaml
Previously, task 1.4.4 did not function correctly. It had a fail-rescue block where it would fail if the password had been kept to "r00tP4ssw0rd" (default) and then the rescue block would change the password anyway. This is not the intended behavior.
Also, checking if the user already has a password is unnecessary as the script has options to not change the password if it is not needed (setting `set_root_password` to false)
> Fixes task 1.4.4

- tasks/section_6_System_Maintenance.yaml
Fixes the name an error with the following output
`fatal: [node-1]: FAILED! => {"msg": "'output_6_2_7' is undefined"}`
`output_6_2_7` had been renamed to `output_6_2_7_folders` and `output_6_2_7_files` but the "correct file permissions" task had not been changed
> Fixes task 6.2.7

- tasks/section_3_Network_Configuration.yaml
We have seen that in some cases, the "martians" settings are being taken from the /etc/ufw/sysctl file, overriding the default files. 
This PR comments the relevant lines in /etc/ufw/sysctl.
> chore: Extends 3.3.4 to include files used by ufw

- tasks/section_3_Network_Configuration.yaml
bugfix(3.3.4): Corrects regexp to find martians in /etc/ufw/sysctl.conf
Instead of looking for `net/ipv4/conf/.*/log_martians=.*`, the regexp was looking for `net.ipv4.conf.*.log_martians=1`.
We now also always comment the lines, irrespective of whether the active value was 0 or 1.
> bugfix(3.3.4): Corrects regexp to find martians in /etc/ufw/sysctl.conf

- tasks/section_5_Access_Authentication_and_Authorization.yaml
The previous PR (using handlers) didn't really restart the daemon, so I added a new task at the end of the ssh tasks to do it "manually". I tested it and it does restart the daemon.
> bugfix: Ensures ssh daemon is restarted at end of ssh changes

- tasks/section_6_System_Maintenance.yaml
In tasks 6.1.10, 6.1.11, 6.1.12, 6.1.13, 6.1.14, `xargs` is used to change file permissions after finding files with `df` commands. The issue is that with `become: yes`, only the first part of the command is executed with `sudo` but not the second part, so that the `find` sentence of the second part doesn't have access to the files found with the `sudo df` command
`df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -nouser 2> /dev/null && true || true` -> finds nothing
`df --local -P | awk {'if (NR!=1) print $6'} | sudo xargs -I '{}' find '{}' -xdev -nouser` -> finds files
This fix adds `sudo` to the second part of the relevant commands.
> bugfix: Ensures all files to be fixed are found [6.1.10, 6.1.11, 6.1.12, 6.1.13, 6.1.14]

- tasks/section_1_Initial_Setup.yaml
Wrong tag 1.1.1.5 in task's tags:
```
- name: 1.1.1.6 Ensure mounting of squashfs filesystems is disabled
block:
- name: 1.1.1.6 Ensure mounting of squashfs filesystems is disabled
...  
tags:
- section1
- level_1_server
- level_1_workstation
- 1.1.1.5 <<<-------------
- filesystems
- squashfs
- modprobe
> bugfix: Corrects task 1.1.1.6's tag

- tasks/section_3_Network_Configuration.yaml
* `when: IPv6_is_enabled` clause variable should be negated for correct execution of disabling IPv6.
* Corrects sysctl clauses as per CIS:
> bugfix: Corrects task 3.1.1 - Disable IPv6

- tasks/section_4_Logging_and_Auditing.yaml
_4.4 Ensure logrotate assigns appropriate permissions_ only considers /etc/logrotate.conf and not the configuration files in /etc/logrotate.d/. This PR adds this and also slightly changes the original regexp to take whitespace into account.
Before:
```
ubuntu@hardening:/etc/logrotate.d$ grep create *
alternatives:create 0640 root root
btmp:    create 0660 root utmp
dpkg:create 0640 root root
wtmp:    create 0664 root utmp
```
After:
```
ubuntu@hardening:/etc/logrotate.d$ grep create *
alternatives: create 0640 root root
btmp:     create 0640 root utmp
dpkg: create 0640 root root
wtmp:     create 0640 root utmp
> feature: Extends task 4.4 to take files in logrotate.d in consideration.

- README.md
- index.html
- tasks/section_1_Initial_Setup.yaml
- tasks/section_5_Access_Authentication_and_Authorization.yaml
Task "Ensure sudo is installed" got moved around in the latest CIS to 5.2.1. This PR fixes the consistency.
> chore: Moves "Ensure sudo is installed" to section 5

- tasks/section_3_Network_Configuration.yaml
Previous version was not working as expected, because if `IPV6_is_enabled` was false (as it is by default), this condition would execute (because of `not IPV6_is_enabled`) and write `/etc/sysctl.conf`, causing an error.
Manual execution is the following:
```
$ sudo sysctl net.ipv6.conf.all.disable_ipv6=1
sysctl: cannot stat /proc/sys/net/ipv6/conf/all/disable_ipv6: No such file or directory
```
Ansible execution is the following 
```
TASK [CIS-Ubuntu-20.04-Ansible : 3.1.1 Disable IPv6] **************************************************************************************************************************************
failed: [node-1] (item={'name': 'net.ipv6.conf.all.disable_ipv6', 'value': 1}) => {"ansible_loop_var": "item", "changed": false, "item": {"name": …
```
> fix for ipv6 logic

- defaults/main.yml
- tasks/section_5_Access_Authentication_and_Authorization.yaml
In some particular use cases (e.g. installing and using new python packages after hardening), it is required that umask permissions were not as strict as 027, because the system will not be able to run the newer python packages. In those cases, it would be better to be able to set the default umask permissions needed for the use case.
Created new variable (`umask_value`) and defaulting to `027` (as most users just need the default configuration)
> Customizable umask value

- defaults/main.yml
Latest PR had a typo, umask_value should be "027" instead of 027 because its value is not taken as a string,
> fixing umask_value to be a string

- tasks/section_3_Network_Configuration.yaml
- tasks/section_4_Logging_and_Auditing.yaml
After touching `/etc/default/grub`, `update-grub` should be executed in tasks 3.1.1,4.1.1.3,4.1.1.4.
Note: I have a doubt with the `when` clause in  3.1.1:
`when: IPv6_is_enabled`
Shouldn't it be  `when: not IPv6_is_enabled` ? (even though it seems that if a priori no IPv6 is available, the `sysctl` commands fail)
> bugfix(3.1.1,4.1.1.3,4.1.1.4): Executes `update-grub` after modifying `/etc/default/grub`.

- tasks/section_3_Network_Configuration.yaml
bugfix(3.1.1): Task 3.1.1 should only run when IPv6 is NOT enabled. Right now it states `when: IPv6_is_enabled`
Also, the CIS documentation states to switch off IPv6 OR through grub, or through `sysctl`. If a priori IPv6 was already disabled, the `sysctl` commands throw an error, hence an `ignore_errors: true` was added in that subtask:
```
TASK [CIS-Ubuntu-20.04-Ansible : 3.1.1 Disable IPv6 - change sysctl] *****************************************************************************************
failed: [node-1] (item={u'name': u'net.ipv6.conf.all.disable_ipv6', u'value': 1}) => {"ansible_loop_var": "item", "changed": false, "item": {"name": "net.ipv6.conf.all.disable_ipv6", "value": 1}, "msg": "Failed to reload sysctl: net.ipv4.conf.all.accept_redirects = …
```
> bugfix(3.1.1): Task 3.1.1 should only run when IPv6 is NOT enabled

- tasks/section_3_Network_Configuration.yaml
In some cases, executing task 3.1.1 throws error, because the reload of `sysctl` doesn't work if the file already has lines with ipv6 stuff and IPv6 has been disabled.
This PR adds a check to overcome this.
> bugfix(3.1.1): Avoids occasional errors, when IPv6 is already disabled.

- tasks/section_1_Initial_Setup.yaml
Many tasks do an apt install without an apt update, which may cause "Unable to fetch some archives" errors if the upstream .debs have changed.
```
whitestack@TC-MXTLNE1-INFR001:~$ sudo apt install systemd-coredump
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
alembic cinder-common docutils-common ieee-data javascript-common libblas3 libevent-core-2.1-7 libevent-pthreads-2.1-7 libgfortran5 libimagequant0 libisns0 libjbig0 libjpeg-turbo8 libjpeg8 libjs-jquery libjs-sphinxdoc
libjs-underscore liblapack3 liblcms2-2 libopts25 libpaper-utils libpaper1 libpq5 libtiff5 libwebp6 libwebpdemux2 libwebpmux3 os-brick-common pycadf-common python-babel-localedata …
```
> chore: Adds a pre-emptive 'apt update'

- tasks/section_5_Access_Authentication_and_Authorization.yaml
If a `Match Address` is added in the middle of the `/etc/ssh/sshd_config` file, the ssh daemon can't be restarted.
Cf. https://unix.stackexchange.com/questions/573792/match-user-placement-in-sshd-config
A quick fix is adding the section at the end of the file.
> bugfix(5.3.10): Corrects "Match Address" section placement in ssh config file

- tasks/section_5_Access_Authentication_and_Authorization.yaml
The previous fix for 5.3.10 (adding the `PermitRootLogin` section at the end of the ssh config file) didn't work well together with the other tasks in the playbook, because those tasks append other lines to the files, so the "Match" section still remains "unclosed" and the ssh daemon can’t restart.
The new fix now closes the "Match" section with a "Match All", so that it can be placed in the middle of the file.
> bugfix(5.3.10): Corrects previous fix

- tasks/section_5_Access_Authentication_and_Authorization.yaml
If package `libpam-pwquality` isn't available on target machine, the passwd quality check fails:
```
ubuntu@hardening:~$ sudo apt-get remove  -y  cracklib-runtime
...
0 upgraded, 0 newly installed, 0 to remove and 92 not upgraded.
ubuntu@hardening:~$ sudo passwd ubuntu
New password: 
/var/cache/cracklib/cracklib_dict.pwd.gz: No such file or directory
BAD PASSWORD: The password fails the dictionary check - error loading dictionary
Retype new password: 
```
After reinstalling:
```
sudo passwd ubuntu
New password: 
Retype new password: 
Password has been already used.
passwd: password updated successfully
```
> bugfix(5.4.1): Installs a missing package so that password quality check doesn't fail

- defaults/main.yml
- tasks/section_3_Network_Configuration.yaml
The flag `IPv6_is_enabled` disables IPv6 through Grub AND in the /etc/sysctl.conf file, which causes problems rerunning the hardening after a reboot, because the config file shouldn't contain entries for IPv6 if IPv6 is already disabled through Grub, and in that case the second part of the block fails. Previously we added a rough workaround for that, but in the end a new flag seems better (and also allows for personalizing).
The block becomes:
```
block:
- name: 3.1.1 Disable IPv6 - change /etc/default/grub
replace:
dest: /etc/default/grub
regexp: '^(GRUB_CMDLINE_LINUX=(?!.*ipv6.disable)\"[^\"]*)(\".*)'
replace: '\1 ipv6.disable=1\2'
when: disable_IPv6_in_grub
- name: 3.1.1 Disable IPv6 - update grub
shell: update-grub
when: disable_IPv6_in_grub
- name: 3.1.1 Disable IPv6 - change sysctl …
```
> chore: Adds a new flag to toggle the disabling of IPv6 through Grub

- defaults/main.yml
- tasks/section_5_Access_Authentication_and_Authorization.yaml
Adding parameter to enable (by default) or disable adding `sesion optional pam_umask.so` in `/etc/pam.d/common-session`
> adding parameter in common-session

- tasks/section_3_Network_Configuration.yaml
- Changes ufw ipv6 configuration in case ipv6 is not enabled
Changes to be committed:
modified:   tasks/section_3_Network_Configuration.yaml
> Removing ipv6 ufc directives

- tasks/section_5_Access_Authentication_and_Authorization.yaml
Sometimes, the previous PAM policy may be more efficient than the one suggested by CIS hardening guidelines. While this is not always the case, the proposed regular expression offers a superior solution that can accommodate all scenarios, allowing users and sysadmins to keep their existing policies intact, while only modifying the encryption method.
Regex tested using regexr.com
> optimized regex

- tasks/section_5_Access_Authentication_and_Authorization.yaml
- Improves 5.4.3: password history with 5 remembered passwords should be inserted after the existing password requisite line
> Fixes password history requirement in PAM configuration

- tasks/section_5_Access_Authentication_and_Authorization.yaml
Tests Before fixing:
Literal values \1 and \3 were written
```
password        requisite                       pam_pwquality.so retry=3
password required pam_pwhistory.so remember=5
password [success\1 sha512 \3
```
Tests After Fixing: 
Capture groups \1 and \3 were honored
```
password	requisite			pam_pwquality.so retry=3
password required pam_pwhistory.so remember=5
password [success=1 default=ignore] pam_unix.so  sha512 
```
> Fixing 5.4.3 and 5.4.4

- tasks/section_5_Access_Authentication_and_Authorization.yaml
Instead of saving the output for a manual revision, it ensures that the file exists and its only content is "console"
> bugfix(5.6): ensures root login is restricted to system console

- tasks/section_1_Initial_Setup.yaml
although a whitespace is the default parameter for a split, it seems required for the build to be successful 
(in section 5 there are also uses of split where the whitespace as separator is explicitly specified)
> chore(1.1.24): Adds small fixes to previous PR

- tasks/section_5_Access_Authentication_and_Authorization.yaml
In the default values, `list_of_users` is defined as a list:
And it is used as a list in the task:
However, in tasks 5.5.1.1, 5.5.1.2 and 5.5.1.3, the variable was treated as a string, causing an error during execution:
> bugfix(5.5.1.1+5.5.1.2+5.5.1.3): removes .split() as variable list_of_os_users is already a list
